// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/12/2025, 23.25.05
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["G:/onDev/hdSales/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/onDev/hdSales/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/onDev/hdSales/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/onDev/hdSales/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/onDev/hdSales/app/plugins/**/*.{js,ts,mjs}","G:/onDev/hdSales/app/composables/**/*.{js,ts,mjs}","G:/onDev/hdSales/app/utils/**/*.{js,ts,mjs}","G:/onDev/hdSales/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/onDev/hdSales/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","G:/onDev/hdSales/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","G:/onDev/hdSales/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;